---
format: 
  commonmark:
    variant: -raw_html+tex_math_dollars
    wrap: none
engine: julia
---

# kickstart.nvim

This is my personal Neovim config originally forked from [nvim-lua/kickstart.nvim](https://github.com/nvim-lua/kickstart.nvim). I've started using Neovim in 2025H1, so I'm still very new to this. For this reason, I'm including the following disclaimer here:

> [!WARNING]
> - I'm new to this.
> - You almost definitely do not want to fork this repo for your own config. 
> - I'm currently using this README mostly to jot down notes for myself. 

## Syncing Fork

Syncing can be a little annoying, because I've moved to a more modular structure. Still, for the time being, I'm trying to sync regularly. To do so:

1. Merge updates from [nvim-lua/kickstart.nvim](https://github.com/nvim-lua/kickstart.nvim) into the #updates-from-master branch. 
2. Resolve inevitable conflicts.
3. Merge into #main.

## Julia 

Mason cannot properly install Julia LS. Instead, Julia LS is set up through Julia's own native package manager `Pkg` with a dedicated Julia LS environment:

```lua
-- Use lspconfig API (works on both nvim 0.10 and 0.11)
require('lspconfig').julials.setup {
  capabilities = capabilities,
  on_new_config = function(new_config, _)
    local server_path = vim.fn.expand("~/.julia/environments/nvim-lspconfig")
    if not require('lspconfig.util').path.is_dir(server_path) then
      vim.notify(
        'Julia LS: Creating environment at ' .. server_path,
        vim.log.levels.INFO
      )
      vim.fn.system({
        'julia',
        '--startup-file=no',
        '--history-file=no',
        '--project=' .. server_path,
        '-e',
        'using Pkg; Pkg.add("LanguageServer"); Pkg.add("SymbolServer")',
      })
    end
  end,
}
```

The environment is created as follows:

```bash
julia --project=~/.julia/environments/nvim-lspconfig -e 'using Pkg; Pkg.add("LanguageServer"); Pkg.add("SymbolServer")'
```

If everything is set up correctly, you should have autocomplete in the following Julia cell:

```{julia}
println("hello")
```

> [!warning] Deprecated `lspconfig` API
> This is using the `lspconfig` API which will be deprecated in future versions of nvim. 

## Best Practices ... maybe

### Lazy 

- Use `opts` to specify config options. Use `config` only for more complex configurations. 
